### ISSUE TITLE
Add Desktop support?

### ISSUE THREAD

**Issue by UNIcodeX** [WangYng/better_sound_effect#1]
On windows, and presumably Linux and Mac, I get the following:

`PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))`

I expected this since I didn't see folders for desktop platforms in your plugin directories, but tried it out anyway.

Would it be possible to add Desktop support for your plugin?

**Comment by WangYng** [comment]
This plugin has not been implemented on these platforms yet. I'm not familiar with Windows and Linux.
